### DISCUSSION TITLE
Support completions and hovers for classes in native CSS layers

### DISCUSSION THREAD

**Discussion by Kcko** [tailwindlabs/tailwindcss-intellisense#1452] [Ideas]
Hi,

Similar issue but unfinished: https://github.com/tailwindlabs/tailwindcss-intellisense/issues/1188

I'm looking for a way to make it so that intellisense will also show custom components (custom classes).

In version 3 it could be done like this: https://dev.to/glocore/tip-add-typography-as-components-to-your-tailwind-config-4l4c

But it's an awkward way, not convenient to write just for the sake of hinting components and classes in a .js file.

Is it possible to modify intellisense to hint everything under @layer utilities/components?

In the topic above it says @layer utility sees it, but that's not the right place under components after all.

Please respond, is this the only thing bothering me about this great plugin since the first time I used it.

**Comment by thecrypticace** [comment]
Things work this way because CSS placed inside `@layer utilities`, `@layer components`, or `@layer whatver-name-it-is` are not actual "utilities" known to Tailwind CSS v4. Meaning they don't get support for variants, modifiers, being marked as important, prefixing, etc… To do that you must use `@utility`. (and v3 never supported reading utilities from CSS files in IntelliSense anyway)

I prototyped arbitrary class suggestions last week to see what it'd take and _it is possible_ but it's not performant at all. Adding several milliseconds to the generating completions for even a project with one small CSS file. There's also a number of edge cases that need to be handled like not showing these suggestions when a variant has been typed. Ultimately, I'll need to add some APIs to Tailwind CSS itself before we can add this feature but *it is planned*.

**Comment by Kcko** [comment]
> _it is planned_.

Great! 

I'm not going to bother with this anymore, but where can I read about this? I want to know in the first wave, I'll keep checking, it's really important to me (I'm sure it is to others).

Thanks for the info and good luck with the development :)

**Comment by Kcko** [comment]
I tried it out today and it still doesn't seem to suggest.

Is there any progress or is it still the same?

Thanks for the response.

https://is.gd/XJExSY

**Comment by Kcko** [comment]
And the second thing, it doesn't tell me at all in @theme to tailwind available classes (for example for overriding, or if I want to make a new property (e.g. breakpoint) so I want to see what are available and what is the name of the variable anyway).

Is this behaviour OK?


https://is.gd/im0nap

**Comment by thecrypticace** [comment]
The suggestions inside `@theme` need to be improved and reworked a bit. This is a known limitation currently.

**Comment by EKliptus** [comment]
On vscode :
I don't have any intellisense related to of my custom color variable declare in @theme and @utility.
Is it the same subject as this issue ?

**Comment by thecrypticace** [comment]
@EKliptus Can you provide an example?

**Comment by tresorama** [comment]
## QUESTION 1: Is this correct? Never studied the tailwind v4 internals

For what I can understand 
```
@utility my-effect { 
// ... 
}
``` 
does 2 things:
- add the css classe to the `@layer utilities` of the CSS
- is readable from the VsCode extension (intellisense)

Instead, this
```
@layer utilities  {
  .my-effect {
    // ...
  }
}
```
- add the css classe to the `@layer utilities` of the CSS (same as before)
- IS NOT readble by the extension

## QUESTION 2: How can we add a new layer between existing layers ?

Inspecting the CSS from dev toools, tailwind cretae this layer order
```css
@layer theme, base, components, utilities;
```

How can we have something like this?
```css
@layer theme, base, components, my-new-layer, utilities;
```

## QUESTION 3: Can `@utility` put the CSS classes not inside the default `utilities` layer but in an other?

I'm here because in my project i want to create semantic classes for typography, that can be overridden by common utilities, so the idea is to put them in a layer like `base` or `components` (or a custom layer) that has lower priority that `utilities` layer.

```css
@utility typo-gigantic {
  @apply text-3xl font-bold lg:text-5xl;
}
```

```tsx
<div className="typo-gigantic text-xs" />
```

**Reply by rozsazoltan** [reply]
In v4, `@utility` is the correct approach, and manual class declarations inside `@layer utilities` should be avoided. (They will work, but may cause issues, for example when using `@apply` or variants.) Some may interest you:
* https://www.reddit.com/r/tailwindcss/comments/1oe6pdt/comment/nkz4xim
* https://www.reddit.com/r/tailwindcss/comments/1opsvea/comment/nnduxx2
* [How to can create (functional) utilities with `@utility` without plugin](https://stackoverflow.com/a/79771971/15167500)
* [Combining multiple utilities to avoid code duplication; attaching a prefix to --value due to utility name shortening](https://stackoverflow.com/q/79656981/15167500)
* [Why not working {min-,max-,}w-screen-{breakpoint} following the pattern of {min-,max-,}w-{container_breakpoint}](https://stackoverflow.com/q/79731898/15167500)
* https://www.reddit.com/r/tailwindcss/comments/1obm0oo/comment/nkkb2ad

<hr>

A new layer can be added like this:
* [How can I insert a custom layer between TailwindCSS's default base, components and utilities layers?](https://stackoverflow.com/a/79714576/15167500)

<hr>

```css
@utility typo-gigantic {
  @apply text-3xl font-bold lg:text-5xl;
}
```

<img width="571" height="790" alt="image" src="https://github.com/user-attachments/assets/5b64cbd4-175c-4e30-afc0-1fcd5e536f89" />

Avoid using `@apply`:
* [Why stop using @apply](https://stackoverflow.com/a/79449440/15167500) - Avoid using `@apply`, especially in CSS modules; the reason is that in CSS modules you create duplicates, which means that in the end the combined size of all the modules will be larger than a single shared global.css file. In addition, the TailwindCSS compiler performs worse when it has to rebuild multiple separate sources repeatedly.

```css
@utility typo-gigantic {
  font-size: var(--text-xs);
  line-height: var(--tw-leading, var(--text-3xl--line-height));
  @variant lg {
    font-size: var(--text-5xl);
    line-height: var(--tw-leading, var(--text-5xl--line-height));
  }
  --tw-font-weight: var(--font-weight-bold);
  font-weight: var(--font-weight-bold);
}
```

But it will only be stronger than the TailwindCSS utilities because of alphabetical order:

<img width="587" height="546" alt="image" src="https://github.com/user-attachments/assets/4ca4be24-61c6-4bdd-8bb8-cd4a3ce2ba6a" />

Additionally, your `typo-gigantic` utility belongs in the `utilities` layer. The `components` layer is not really needed here anymore. Utilities are generally designed to replace a single parameter, but in your case, you're adding several at once. Because of that, `typo-gigantic` will only be stronger than `text-xs` due to CSS specificity, as it was declared later.

Utilities like this go against the intended use of TailwindCSS. Instead, you should aim for [inline component generation](https://stackoverflow.com/a/79449440/15167500), where you define the element once, for example as `text-3xl font-bold lg:text-5xl`, and that's it. Thanks to reusable component declarations, there is no need for repetition.

> Essentially if you ever find yourself doing something like:
> ```css
> .btn {
>   @apply px-4 py-2 rounded bg-blue-500 text-white;
> }
> ```
> 
> Stop, slap yourself hard, once, and make a `<Button>` component instead:
> ```html
> <button class="px-4 py-2 rounded bg-blue-500 text-white">
>   <slot/>
> </button>
> ```
> 
> Source: [Moni](https://discord.com/channels/486935104384532500/486935104384532502/1417851311113764954)

If you still insist on using CSS, which is a bad idea. In our case, it would be more reasonable to declare `typo-gigantic` inside the `components` layer, because it's not really a utility (even though you're calling it one). It's just a CSS class where you predefine the styles (let's ignore for now that you're doing it with `@apply`).

```css
@layer components {
  .typo-gigantic {
    font-size: var(--text-xs);
    line-height: var(--tw-leading, var(--text-3xl--line-height));
    @variant lg {
      font-size: var(--text-5xl);
      line-height: var(--tw-leading, var(--text-5xl--line-height));
    }
    --tw-font-weight: var(--font-weight-bold);
    font-weight: var(--font-weight-bold);
  }
}
```

This way, `text-xs`, which is in the stronger `utilities` layer, will override the font size of `typo-gigantic` (the `text-3xl lg:text-5xl` declaration). This way, it will be weaker:

<img width="567" height="599" alt="image" src="https://github.com/user-attachments/assets/2243d312-4820-40d1-a41e-8fe6250b4c14" />

This way, with a new layer, it becomes stronger:

```css
/* @import "tailwindcss"; */

@layer theme, base, components, utilities, custom;

@import "tailwindcss/theme.css" layer(theme);
@import "tailwindcss/preflight.css" layer(base);
@import "tailwindcss/utilities.css" layer(utilities);

@layer custom {
  .typo-gigantic {
    font-size: var(--text-xs);
    line-height: var(--tw-leading, var(--text-3xl--line-height));
    @variant lg {
      font-size: var(--text-5xl);
      line-height: var(--tw-leading, var(--text-5xl--line-height));
    }
    --tw-font-weight: var(--font-weight-bold);
    font-weight: var(--font-weight-bold);
  }
}
```

<img width="602" height="650" alt="image" src="https://github.com/user-attachments/assets/083340b8-d8ef-448a-8084-d7ab546e7972" />

But the best solution is not to declare classes for components at all. Instead, define the component's styling directly in the inline class attribute, so you don't have to deal with overrides. For component handling, may interest you:
* [Tailwind CSS, class precedence is not respected](https://stackoverflow.com/a/79725940/15167500)
* [How do you reference dynamic classes/utilities using a JS variable and pass them through in the class attribute inline in HTML?](https://stackoverflow.com/q/79769249/15167500)
* [How to build dynamically class names with Tailwind CSS](https://stackoverflow.com/a/79745137/15167500)
