### ISSUE TITLE
Conflicts not always showing in v4 projects

### ISSUE THREAD

**Issue by thecrypticace** [tailwindlabs/tailwindcss-intellisense#1047]
See https://github.com/tailwindlabs/tailwindcss/discussions/14361

I've been able to reproduce this myself under certain conditions as well:

```css
/* app.css */

@import "tailwindcss";

@theme {
  --width-8xl: 90rem;
  --color-neon-pink: oklch(71.7% 0.25 360);
}
```

```html
<div class="foo max-w-7xl max-w-8xl hover:underline">testing</div>
<div class="max-w-6xl max-w-7xl max-w-8xl">testing</div>
<div class="line-through underline">testing</div>
<div class="p-4 p-12">testing</div>
```

The first class list does not report conflicts
