### ISSUE TITLE
Custom @import breaks Intellisense on v4 beta

### ISSUE THREAD

**Issue by florianbouvot** [tailwindlabs/tailwindcss-intellisense#1103]
**What version of VS Code are you using?**

v1.95.3

**What version of Tailwind CSS IntelliSense are you using?**

v0.12.15

**What version of Tailwind CSS are you using?**

v4.0.0-beta.4

**What package manager are you using?**

pnpm

**What operating system are you using?**

macOS

**Tailwind config**

Config via main CSS file

```css
@import 'tailwindcss';
@import './base/reset.css' layer(base);
@import './base/webfont.css' layer(base);
@import './components/skip-link.css' layer(components);
@import './components/container.css' layer(components);
@import './components/breakout.css' layer(components);
@import './components/link-faux.css' layer(components);
@import './components/button.css' layer(components);
@import './components/forms.css' layer(components);
@import './components/prose.css' layer(components);
@import '/node_modules/swiper/swiper.min.css' layer(components);
@import '/node_modules/swiper/modules/a11y.min.css' layer(components);
@import '/node_modules/swiper/modules/free-mode.min.css' layer(components);
@import '/node_modules/swiper/modules/navigation.min.css' layer(components);
@import '/node_modules/swiper/modules/pagination.min.css' layer(components);
@import './components/swiper.css' layer(components);

@theme {
  --font-sans: Inter, ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji',
    'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';

  --color-primary-50: var(--color-indigo-50);
  --color-primary-100: var(--color-indigo-100);
  --color-primary-200: var(--color-indigo-200);
  --color-primary-300: var(--color-indigo-300);
  --color-primary-400: var(--color-indigo-400);
  --color-primary-500: var(--color-indigo-500);
  --color-primary-600: var(--color-indigo-600);
  --color-primary-700: var(--color-indigo-700);
  --color-primary-800: var(--color-indigo-800);
  --color-primary-900: var(--color-indigo-900);
  --color-primary-950: var(--color-indigo-950);
}

@plugin '@tailwindcss/forms';
@plugin '@tailwindcss/typography';

/*
  The default border color has changed to `currentColor` in Tailwind CSS v4,
  so we've added these compatibility styles to make sure everything still
  looks the same as it did with Tailwind CSS v3.

  If we ever want to remove these styles, we need to add an explicit border
  color utility to any element that depends on these defaults.
*/
@layer base {
  *,
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    border-color: var(--color-gray-200, currentColor);
  }
}
```

**VS Code settings**

```json
{
  "codesnap.backgroundColor": "transparent",
  "codesnap.boxShadow": "rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0) 0px 0px 0px 0px, rgba(0, 0, 0, 0.1) 0px 10px 15px -3px, rgba(0, 0, 0, 0.05) 0px 4px 6px -2px",
  "codesnap.containerPadding": "1em",
  "editor.accessibilitySupport": "off",
  "editor.bracketPairColorization.enabled": true,
  "editor.fontFamily": "'JetBrains Mono', 'Operator Mono', Menlo, Monaco, 'Courier New', monospace",
  "editor.fontSize": 14,
  "editor.minimap.enabled": false,
  "editor.rulers": [80],
  "editor.tabSize": 2,
  "editor.quickSuggestions": {
    "strings": true
  },
  "diffEditor.useInlineViewWhenSpaceIsLimited": false,
  "diffEditor.experimental.showMoves": true,
  "diffEditor.renderSideBySide": false,
  "files.associations": {
    "*.css": "tailwindcss"
  },
  "terminal.integrated.env.osx": {
    "FIG_NEW_SESSION": "1",
    "CW_NEW_SESSION": "1",
    "Q_NEW_SESSION": "1"
  },
  "workbench.colorTheme": "Atom One Dark",
  "git.autofetch": true,
  "git.confirmSync": false,
  "git.enableSmartCommit": true,
  "editor.codeActionsOnSave": {
    
  },
}
```

**Intellisense output**

```
Locating server…
Booting server...
Setting up server…
Listening for messages…
Searching for Tailwind CSS projects in the workspace's folders.
{"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}}
{"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}}
{"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}}
{"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}}
{"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}}
{"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}}
{"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}}
{"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}}
{"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}}
{"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}}
{"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}}
{"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}}
{"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}}
{"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}}
{"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}}
{"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}}
{"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}}
{"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}}
{"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}}
{"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}}
{"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}}
[Global] Creating projects: [{"folder":"/Users/florian/Herd/edit-starter","config":"/Users/florian/Herd/edit-starter/resources/css/app.css","selectors":[{"pattern":"/Users/florian/Herd/edit-starter/resources/css/app.css","priority":0},{"pattern":"/Users/florian/Herd/edit-starter/resources/css/**","priority":2},{"pattern":"/Users/florian/Herd/edit-starter/**","priority":4}],"user":false,"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}},{"folder":"/Users/florian/Herd/edit-starter","config":"/Users/florian/Herd/edit-starter/resources/css/components/_aos.css","selectors":[{"pattern":"/Users/florian/Herd/edit-starter/resources/css/components/_aos.css","priority":0},{"pattern":"/Users/florian/Herd/edit-starter/resources/css/components/**","priority":2},{"pattern":"/Users/florian/Herd/edit-starter/**","priority":4}],"user":false,"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}},{"folder":"/Users/florian/Herd/edit-starter","config":"/Users/florian/Herd/edit-starter/resources/css/components/_prose.css","selectors":[{"pattern":"/Users/florian/Herd/edit-starter/resources/css/components/_prose.css","priority":0},{"pattern":"/Users/florian/Herd/edit-starter/resources/css/components/**","priority":2},{"pattern":"/Users/florian/Herd/edit-starter/**","priority":4}],"user":false,"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}},{"folder":"/Users/florian/Herd/edit-starter","config":"/Users/florian/Herd/edit-starter/resources/css/components/button.css","selectors":[{"pattern":"/Users/florian/Herd/edit-starter/resources/css/components/button.css","priority":0},{"pattern":"/Users/florian/Herd/edit-starter/resources/css/components/**","priority":2},{"pattern":"/Users/florian/Herd/edit-starter/**","priority":4}],"user":false,"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}},{"folder":"/Users/florian/Herd/edit-starter","config":"/Users/florian/Herd/edit-starter/resources/css/components/forms.css","selectors":[{"pattern":"/Users/florian/Herd/edit-starter/resources/css/components/forms.css","priority":0},{"pattern":"/Users/florian/Herd/edit-starter/resources/css/components/**","priority":2},{"pattern":"/Users/florian/Herd/edit-starter/**","priority":4}],"user":false,"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}},{"folder":"/Users/florian/Herd/edit-starter","config":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/app.css","selectors":[{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/app.css","priority":0},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/**","priority":2},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/**","priority":4}],"user":false,"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}},{"folder":"/Users/florian/Herd/edit-starter","config":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/base/typo.css","selectors":[{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/base/typo.css","priority":0},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/base/**","priority":2},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/**","priority":4}],"user":false,"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}},{"folder":"/Users/florian/Herd/edit-starter","config":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/box.css","selectors":[{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/box.css","priority":0},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/**","priority":2},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/**","priority":4}],"user":false,"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}},{"folder":"/Users/florian/Herd/edit-starter","config":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/button-group.css","selectors":[{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/button-group.css","priority":0},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/**","priority":2},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/**","priority":4}],"user":false,"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}},{"folder":"/Users/florian/Herd/edit-starter","config":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/button.css","selectors":[{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/button.css","priority":0},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/**","priority":2},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/**","priority":4}],"user":false,"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}},{"folder":"/Users/florian/Herd/edit-starter","config":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/card.css","selectors":[{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/card.css","priority":0},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/**","priority":2},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/**","priority":4}],"user":false,"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}},{"folder":"/Users/florian/Herd/edit-starter","config":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/dropdown.css","selectors":[{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/dropdown.css","priority":0},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/**","priority":2},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/**","priority":4}],"user":false,"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}},{"folder":"/Users/florian/Herd/edit-starter","config":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/forms.css","selectors":[{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/forms.css","priority":0},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/**","priority":2},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/**","priority":4}],"user":false,"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}},{"folder":"/Users/florian/Herd/edit-starter","config":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/list.css","selectors":[{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/list.css","priority":0},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/**","priority":2},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/**","priority":4}],"user":false,"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}},{"folder":"/Users/florian/Herd/edit-starter","config":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/listbox.css","selectors":[{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/listbox.css","priority":0},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/**","priority":2},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/**","priority":4}],"user":false,"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}},{"folder":"/Users/florian/Herd/edit-starter","config":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/modal.css","selectors":[{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/modal.css","priority":0},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/**","priority":2},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/**","priority":4}],"user":false,"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}},{"folder":"/Users/florian/Herd/edit-starter","config":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/prose.css","selectors":[{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/prose.css","priority":0},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/**","priority":2},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/**","priority":4}],"user":false,"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}},{"folder":"/Users/florian/Herd/edit-starter","config":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/sidebar.css","selectors":[{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/sidebar.css","priority":0},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/**","priority":2},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/**","priority":4}],"user":false,"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}},{"folder":"/Users/florian/Herd/edit-starter","config":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/slideover.css","selectors":[{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/slideover.css","priority":0},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/**","priority":2},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/**","priority":4}],"user":false,"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}},{"folder":"/Users/florian/Herd/edit-starter","config":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/table.css","selectors":[{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/table.css","priority":0},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/ressources/css/components/**","priority":2},{"pattern":"/Users/florian/Herd/edit-starter/vendor/editcms/edit-cms/**","priority":4}],"user":false,"tailwind":{"version":"4.0.0-beta.4","features":["css-at-theme","layer:base","content-list"],"isDefaultVersion":false}}]
[Global] Preparing projects...
[Global] Initializing projects...
[resources/css/app.css] Initializing...
[Global] Adding watch patterns: /Users/florian/Herd/edit-starter/resources/css/app.css, /Users/florian/Herd/edit-starter/resources/css, /Users/florian/Herd/edit-starter/resources, /Users/florian/Herd/edit-starter
[resources/css/app.css] supported features: ["css-at-theme","layer:base","content-list"]
[resources/css/app.css] Loaded tailwindcss v4.0.0-beta.4: /Users/florian/Herd/edit-starter/node_modules/.pnpm/tailwindcss@4.0.0-beta.4/node_modules/tailwindcss
[resources/css/app.css] Building...
[Global] Initialized 1 projects
```

**Reproduction URL**

I can share my project if needed.

**Describe your issue**

I'm working on PHP project views are powered by twig (.html.twig) and I'm using vite with postcss for Tailwind CSS.

Since Tailwind CSS v4 beta, intellisense doesn't provide any suggestions.
I've try with stable en pre-release version, same results.

Is there something wrong in my config or is it an issue with Intellisense / v4 and twig?

https://github.com/user-attachments/assets/0dbc3088-dda6-416b-8fce-325c0295df11
