### ISSUE TITLE
`--*: initial;` and `--spacing-*: initial;` doesn't remove default theme spacing classes or font classes

### ISSUE THREAD

**Issue by vishucrafts** [tailwindlabs/tailwindcss-intellisense#1133]
**What version of VS Code are you using?**

For example: v1.96.4

**What version of Tailwind CSS IntelliSense are you using?**

0.14.1

**What version of Tailwind CSS are you using?**
4.0.0

**What package manager are you using?**

pnpm

**What operating system are you using?**

macOS

**Describe your issue**

In my global.css I have 

```
@import 'tailwindcss';

@plugin 'tailwindcss-react-aria-components';

@theme {
	--text-*: initial;
	--spacing-*: initial;
	--font-*: initial;
	--font-weight-*: initial;

	--font-sans: var(--font-sans);
	--font-mono: var(--font-mono);

	--font-weight-normal: 400;
	--font-weight-medium: 700;
	--font-weight-bold: 900;

	/* @link https://utopia.fyi/type/calculator?c=320,16,1.125,1240,18,1.2,5,2,&s=0.75|0.5|0.25,1.5|2|3|4|6,s-l&g=s,l,xl,12 */
	--text--2: clamp(0.7813rem, 0.7932rem + -0.0154vw, 0.7901rem);
	--text--1: clamp(0.8889rem, 0.872rem + 0.0845vw, 0.9375rem);
	--text-0: clamp(1rem, 0.9565rem + 0.2174vw, 1.125rem);
	--text-1: clamp(1.125rem, 1.0467rem + 0.3913vw, 1.35rem);
	--text-2: clamp(1.2656rem, 1.1424rem + 0.6163vw, 1.62rem);
	--text-3: clamp(1.4238rem, 1.2429rem + 0.9046vw, 1.944rem);
	--text-4: clamp(1.6018rem, 1.3475rem + 1.2713vw, 2.3328rem);
	--text-5: clamp(1.802rem, 1.4551rem + 1.7345vw, 2.7994rem);

	/* @link https://utopia.fyi/space/calculator?c=320,16,1.125,1240,18,1.2,5,2,&s=0.75|0.5|0.25,1.5|2|3|4|6,s-l&g=s,l,xl,12 */
	--spacing-3xs: clamp(0.25rem, 0.2283rem + 0.1087vw, 0.3125rem);
	--spacing-2xs: clamp(0.5rem, 0.4783rem + 0.1087vw, 0.5625rem);
	--spacing-xs: clamp(0.75rem, 0.7065rem + 0.2174vw, 0.875rem);
	--spacing-s: clamp(1rem, 0.9565rem + 0.2174vw, 1.125rem);
	--spacing-m: clamp(1.5rem, 1.4348rem + 0.3261vw, 1.6875rem);
	--spacing-l: clamp(2rem, 1.913rem + 0.4348vw, 2.25rem);
	--spacing-xl: clamp(3rem, 2.8696rem + 0.6522vw, 3.375rem);
	--spacing-2xl: clamp(4rem, 3.8261rem + 0.8696vw, 4.5rem);
	--spacing-3xl: clamp(6rem, 5.7391rem + 1.3043vw, 6.75rem);

	/* One-up pairs */
	--spacing-3xs-2xs: clamp(0.25rem, 0.1413rem + 0.5435vw, 0.5625rem);
	--spacing-2xs-xs: clamp(0.5rem, 0.3696rem + 0.6522vw, 0.875rem);
	--spacing-xs-s: clamp(0.75rem, 0.6196rem + 0.6522vw, 1.125rem);
	--spacing-s-m: clamp(1rem, 0.7609rem + 1.1957vw, 1.6875rem);
	--spacing-m-l: clamp(1.5rem, 1.2391rem + 1.3043vw, 2.25rem);
	--spacing-l-xl: clamp(2rem, 1.5217rem + 2.3913vw, 3.375rem);
	--spacing-xl-2xl: clamp(3rem, 2.4783rem + 2.6087vw, 4.5rem);
	--spacing-2xl-3xl: clamp(4rem, 3.0435rem + 4.7826vw, 6.75rem);

	/* Custom pairs */
	--spacing-s-l: clamp(1rem, 0.5652rem + 2.1739vw, 2.25rem);
}
```

When I use `--text-*: initial` it removes default text sizing utilities however `--spacing-*: initial` doesn't remove default spacing utilities for padding, margins, space etc. Tailwind doesn't generate old classes for example px-2 doesn't work but it still shows up in suggestions.

I also noticed `--font-*: initial;`, `--font-weight-*: initial;` don't remove default utility suggestions either. 

`--*: initial;` should remove all default theme classes where necessary.

**Comment by FredericoC** [comment]
Can confirm;

<img width="1058" alt="Image" src="https://github.com/user-attachments/assets/0ce68bc1-48fa-4e49-a63f-f02db15a7307" />

**Comment by thecrypticace** [comment]
Hey, this will be fixed in the next version of Tailwind CSS. Thanks for reporting it. ✨

**Comment by vincerubinetti** [comment]
Does anyone know if there has been a regression on this? I'm seeing this in the latest version as of writing (even with a vscode restart).

```css
@import "tailwindcss";

@theme {
  --spacing-*: initial;
  --spacing: 0.25rem;
  --spacing-1: 0.25rem;
  --spacing-2: 0.5rem;
  --spacing-4: 1rem;
  --spacing-8: 2rem;
  --spacing-12: 3rem;
  --spacing-16: 4rem;
  --spacing-20: 5rem;
  --spacing-24: 6rem;
  --spacing-32: 8rem;
  --spacing-40: 10rem;
  --spacing-48: 12rem;
  --spacing-64: 16rem;
  --spacing-80: 20rem;

  --font-serif: "Source Serif 4 Variable", serif;
  --font-sans: "Figtree Variable", sans-serif;
  --font-mono: "Sometype Mono Variable", monospace;

  --font-weight-*: initial;
  --font-weight-normal: 350;

  --radius-*: initial;
  --radius-md: 10px;

  --color-*: initial;
  --color-theme: oklch(60% 0.15 240);
  --color-secondary: oklch(60% 0.15 60);
}
```

Perhaps I'm doing something wrong here? Like is `--spacing: 0.25rem` messing with it somehow? I needed to add that though to make TW not error when using the `--spacing()` function in arbitrary values e.g. `px-[calc(100%+--spacing(2))]`.

<img height="200" alt="Image" src="https://github.com/user-attachments/assets/11f7847d-3b89-4c11-8b8b-c7afa1f0c863" />

<img height="200" alt="Image" src="https://github.com/user-attachments/assets/8cd654d4-6ba7-4c76-a98d-1eb48a0b8094" />
