### ISSUE TITLE
No suggestions for custom components after migrating to tailwind v4

### ISSUE THREAD

**Issue by ramrami** [tailwindlabs/tailwindcss-intellisense#1148]
What version of VS Code are you using?
1.96.2

What version of Tailwind CSS IntelliSense are you using?
0.14.1

What version of Tailwind CSS are you using?
4.0.0

What package manager are you using?
npm

What operating system are you using?
macOS

**Reproduction URL**

https://play.tailwindcss.com/ASo0oIbcaC

**Describe your issue**

IntelliSense doesn't work anymore for custom components after migrating from the JS config to the CSS config using `@layer components`

**Comment by thecrypticace** [comment]
Hey, so v4 uses native CSS cascade layers and as such no longer hijacks _any_ use of `@layer`. Because of this, in v4, you no longer write custom utilities and components using `@layer components` or `@layer utilities`. Instead they're both written using `@utility` instead:

```css
@utility outer {
  padding-left: var(--spacing);
  padding-right: var(--spacing);
}

@utility inner {
  width: 100%;
  max-width: 400px;
  margin-left: auto;
  margin-right: auto;
}
```

We mention this in the [upgrade guide](https://tailwindcss.com/docs/upgrade-guide#adding-custom-utilities) when talking about `@layer utilities` but I think we need to clarify that it _also_ applies to `@layer components` as well.

See this Play: https://play.tailwindcss.com/mzRlNIQhgT?file=css

You'll see that hovers and completions work as expected once you switch to the new syntax:

<img width="488" alt="Image" src="https://github.com/user-attachments/assets/362e7133-ec71-4039-ab63-498b79f0d536" />
<img width="652" alt="Image" src="https://github.com/user-attachments/assets/8b220e88-27cc-41ae-8dd6-830e6de6c8d6" />
