### ISSUE TITLE
`--leading-*: initial;` does not remove classes from completion

### ISSUE THREAD

**Issue by unional** [tailwindlabs/tailwindcss-intellisense#1173]
**What version of VS Code are you using?**

For example: v1.78.2

**What version of Tailwind CSS IntelliSense are you using?**

0.14.3

**What version of Tailwind CSS are you using?**

4.0.3

**What package manager are you using?**

pnpm

**What operating system are you using?**

macOS

**Tailwind config**

```css
@import "tailwindcss";

@theme {
	--leading-*: initial;
}
```

**Reproduction URL**

[Tailwind Play](https://play.tailwindcss.com/EcFyx7C3Vm?file=css)

**Describe your issue**

I want to define our own leading (`line-height`) based on our design tokens.

`--leading-*: initial;` doesn't do the same thing as `--color-*: initial;`,
and the completion still shows the default values:

![Image](https://github.com/user-attachments/assets/6b853d72-dfa0-47c3-b564-ddc01bdbc100)

I can understand why as the default implementation of `leading-*` is computed from `--spacing`:

```css
.leading-1 {
	--tw-leading: calc(var(--spacing) * 1);
	line-height: calc(var(--spacing) * 1);
}
```

I think it is also a bug in `tailwindcss` itself.

**Comment by thecrypticace** [comment]
Hi! This is showing up because the `leading-*` utilities also read from the spacing scale. The way to remove these suggestions is to _also_ reset the spacing scale:

```css
@import "tailwindcss";

@theme {
  --spacing: initial;
  --leading-*: initial;
}
```

see here: https://play.tailwindcss.com/mOoCIPqjpi

<img width="709" alt="Image" src="https://github.com/user-attachments/assets/8f63d3af-2856-46d2-9ba6-60eff40aa0a8" />

**Comment by unional** [comment]
Thanks. Since other classes such as `p` and `m` are also read from the spacing scale, doing this means those will also be gone and I have to define all of them manually?

**Comment by thecrypticace** [comment]
It does mean that they'd be gone.

However, even if you re-define the spacing scale:
```css
@import "tailwindcss";

@theme {
  --leading-*: initial;
  --spacing: initial;
  --spacing-1: 1rem;
  --spacing-2: 2rem;
  --spacing-3: 3rem;
  --spacing-4: 4rem;
  --spacing-5: 5rem;
}
```

you will still get suggestions for the defined `--spacing-*` values in `leading-*` utilities:

<img width="701" alt="Image" src="https://github.com/user-attachments/assets/564f7c54-1325-4860-9e3c-4d54e8e85055" />


The leading utility reads from the spacing scale so you're going to get suggestions for these values when they exist.
