### ISSUE TITLE
tailwindcss-intellisense does not suggest custom classes for tailwindcss v4

### ISSUE THREAD

**Issue by jabed-web-dev** [tailwindlabs/tailwindcss-intellisense#1188]
**tailwindcss-intellisense Installation**
Identifier: _bradlc.vscode-tailwindcss_
Version: _0.14.3_
Last Updated: _2025-02-09, 21:43:44_

```json
"dependencies": {
    "@tailwindcss/vite": "^4.0.5",
    "tailwindcss": "^4.0.5"
}
```

```css
@import "tailwindcss";

@layer components {
  .card {
    background-color: var(--color-white);
    border-radius: var(--rounded-lg);
    padding: var(--spacing-6);
    box-shadow: var(--shadow-xl);
  }
}
```

**Comment by thecrypticace** [comment]
Hi! In v4 we are no longer hijacking CSS's native `@layer` directive. (We're actually making use of native CSS layers in v4).

Because of this these are *not* utilities — its just raw CSS.

You should instead write the above like this:

```css
@import "tailwindcss";

@utility card {
  background-color: var(--color-white);
  border-radius: var(--rounded-lg);
  padding: var(--spacing-6);
  box-shadow: var(--shadow-xl);
}
```

I think we forgot to mention this in the upgrade guide — I'll get that updated today or tomorrow 👍
