### ISSUE TITLE
Color swatch not showing up for variables using theme

### ISSUE THREAD

**Issue by unional** [tailwindlabs/tailwindcss-intellisense#1210]
You can see in the following screenshot that the color swatch is showing up correctly for `twds:text-red-500`, but not for `twds:text-red` which reference the same variable:

![Image](https://github.com/user-attachments/assets/abaef3bb-533a-4fb9-8bb3-2a0dfdee4326)

**Comment by thecrypticace** [comment]
Ah, we need to evaluate theme functions defined in theme variables

**Comment by ShayanTheNerd** [comment]
I'm not sure if this is the same issue, but I have a similar problem. 

Using this configuration:
```css
:root {
  --primitive-sky-500: #05a8ff;
}

@theme inline {
  --color-*: initial;
  --color-status-info: var(--primitive-sky-500);
}
```
The color swatch doesn't show up next to, for example, the utility `bg-status-info`. This isn't a problem when the variable is declared within `@theme`, like this:
```css
@theme inline {
  --primitive-sky-500: #05a8ff;

  --color-*: initial;
  --color-status-info: var(--primitive-sky-500);
}
```
However, it'd be cleaner to have the variables declared outside of `@theme` to explicitly separate them from Tailwind's utilities.
