### ISSUE TITLE
Tailwind CSS IntelliSense not work with tailwindcss4.0

### ISSUE THREAD

**Issue by 527430408** [tailwindlabs/tailwindcss-intellisense#1245]
**What version of VS Code are you using?**

For example: v1.78.2

**What version of Tailwind CSS IntelliSense are you using?**

For example: v0.7.0

**What version of Tailwind CSS are you using?**

For example: v2.0.4

**What package manager are you using?**

For example: npm, yarn

**What operating system are you using?**

For example: macOS, Windows

**Tailwind config**

```js
// Paste the contents of your Tailwind config file here
```

**VS Code settings**

```json
// Paste your VS Code settings in JSON format here
```

**Reproduction URL**

A public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways.

**Describe your issue**

Describe the problem you're seeing, any important steps to reproduce and what behavior you expect instead

**Comment by 527430408** [comment]
![Image](https://github.com/user-attachments/assets/b270073a-8bf5-491a-8155-d1c0d7806047)

**Comment by Kcko** [comment]
Same for me, absolutely without any suggestion. (Im on testing project with Tailwind CLI without any JS).

Short video: https://is.gd/NdKORW

**Comment by Kcko** [comment]
Temporary solution.  https://github.com/tailwindlabs/tailwindcss-intellisense/issues/1153#issuecomment-2635462093

You don't need to create tailwind.config.js (it's useless - TW4 doesn't work with it anymore).

Just reload the window -> ctrl + shift + P > Reload window

**Short video:**  -> https://is.gd/fxEzNm

**Comment by Kcko** [comment]
But reaload does not solve everythink -> https://is.gd/dAHXZo

**Comment by lihanspace** [comment]
I am using `postcss` and `@tailwindcss/postcss`.

src/assets/styles/tailwind.css

```css
@import "element-plus/dist/index.css";
@import "tailwindcss/theme.css";
@import "./reset.css";
@import "./variables.css";
@import "./globals.scss";
@import "./element-plus-custom.scss";

body.body {
  @import "tailwindcss/utilities.css";
}
```

src/assets/styles/element-plus-custom.scss

Tailwind CSS IntelliSense not work

```scss
.el-form--inline {
  .el-form-item {
    // .el-form-item__content {
    //   width: var(--el-form-inline-content-width);
    // }
    .el-input, .el-cascader, .el-select, .el-autocomplete {
      width: var(--el-form-inline-content-width);
    }
  }
}
.el-button.is-link + .el-button.is-link {
  margin-left: 4px;
}
```

Tailwind CSS IntelliSense work

```scss
.el-form--inline {
  .el-form-item {
    /* .el-form-item__content {
      width: var(--el-form-inline-content-width);
    } */
    .el-input, .el-cascader, .el-select, .el-autocomplete {
      width: var(--el-form-inline-content-width);
    }
  }
}
.el-button.is-link + .el-button.is-link {
  margin-left: 4px;
}
```
