### ISSUE TITLE
Duplicate suggestion appears when a class is declared using @theme and then extended with a weaker @utility

### ISSUE THREAD

**Issue by rozsazoltan** [tailwindlabs/tailwindcss-intellisense#1313]
**What version of VS Code are you using?**

v1.99.2

**What version of Tailwind CSS IntelliSense are you using?**

v0.14.15

**What version of Tailwind CSS are you using?**

v4.1.3

**What package manager are you using?**

pnpm

**What operating system are you using?**

Windows 11 with WSL (CentOS Stream 9)

**Reproduction URL**

**index.css**
```css
@import "tailwindcss";

@theme {
  --text-subheader: 0.75rem;
  --text-subheader--line-height: 1rem;
  --text-subheader--letter-spacing: 0.25rem;
  --text-subheader--font-weight: 600;
}

@utility text-subheader {
  text-transform: uppercase;
}
```

**index.js**
```js
import './index.css'

console.log(`
  <div class="text-subhe">
`)
```

**Describe your issue**

I declared a text style called `subheader`. Since passing nested keys is limited, I declared the additional uppercase separately in a weaker utility as a 'new' class. In the end, these get merged because they share the same name, so it's pointless for IntelliSense to show a duplicate hint.

![Image](https://github.com/user-attachments/assets/3b86145e-c87a-42ae-9a24-57795c814091)

**Related**

* https://github.com/tailwindlabs/tailwindcss/discussions/16317#discussioncomment-12817719

**Extra**

I know that the strange duplication is caused by the fact that I redeclare a separate utility named `.text-subheader` on top of the `.text-subheader` declared in `@theme`; this can also be seen in the playground hint.

Still, it doesn't make sense to show two identical suggestions, even if they're coming from two different sources.

* https://play.tailwindcss.com/Lwqss6zmTS

![Image](https://github.com/user-attachments/assets/602477b4-1554-4ec6-9dfd-d1c289f4739e)
