### ISSUE TITLE
Classes in globals.css not appear in autocompletion

### ISSUE THREAD

**Issue by hallee9000** [tailwindlabs/tailwindcss-intellisense#1318]
**What version of Cursor are you using?**

0.48.9 (Universal)

**What version of Tailwind CSS IntelliSense are you using?**

0.14.15

**What version of Tailwind CSS are you using?**

4.0.12

**What package manager are you using?**

pnpm

**What operating system are you using?**

macOS 14.6.1

**Tailwind config**

src/app/globals.css

```css
@import 'tailwindcss';
@import './theme.css';
@plugin "@tailwindcss/typography";

body {
  font-family: var(--font-geist-sans), PingFang SC, PingFang, Lantinghei SC, HiraginoSansGB-W3, Microsoft Yahei, Helvetica Neue, Helvetica, Arial, sans-serif;
  @apply text-sm leading-6 text-primary bg-base;
}

a {
  @apply text-secondary;
  &:hover {
    @apply text-primary;
  }
}

@utility link-brand {
  @apply text-brand!;
  &:hover {
    @apply text-brand-2! underline!;
  }
}

@utility text-balance {
  text-wrap: balance;
}

@utility scrollbar-thin {
  scrollbar-width: thin;
}

div[data-radix-popper-content-wrapper] {
  z-index: 1000!important;
}
```

**Describe your issue**

The class (like `link-brand`) in globals.css doesn't appear in autocompletion.
