### ISSUE TITLE
Tailwind CSS LSP Not Working in Cloned Laravel Project

### ISSUE THREAD

**Issue by end3r-man** [tailwindlabs/tailwindcss-intellisense#1322]
**What version of VS Code are you using?**

Im using neovim

**What version of Tailwind CSS IntelliSense are you using?**

v0.14.15

**What version of Tailwind CSS are you using?**

v4.1.4

**What package manager are you using?**

npm

**What operating system are you using?**

linux

**Tailwind config**

```css
@import url('https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap');
@import "tailwindcss";

@plugin "@iconify/tailwind4";
@plugin "daisyui" {
  themes: light --default;
}

@source "../views";
@source "../views/**/*.blade.php";
@source '../../vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php';
@source '../../storage/framework/views/*.php';
@source '../**/*.blade.php';
@source '../**/*.js';

@theme {
    --font-sans: 'Instrument Sans', ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji',
        'Segoe UI Symbol', 'Noto Color Emoji';
}
```

**Nvim Code settings**

```lua
			tailwindcss = {
				filetypes = {
					"html",
					"blade",
					"javascript",
					"typescript",
					"vue",
					"javascriptreact",
					"typescriptreact",
				},
			},
```

**Describe your issue**

 i'm encountering an issue with the Tailwind CSS Language Server Protocol (LSP) in my Laravel project. Here's a breakdown of the problem:

Issue Description:

    When I create a new Laravel project with Tailwind CSS v4, the Tailwind CSS LSP works perfectly. I can get autocompletion without any issues.

    However, when I clone an existing Laravel project from a Git repository that also uses Tailwind CSS v4, the Tailwind CSS LSP stops working. I don't get any autocompletion suggestions.
