### ISSUE TITLE
Tailwind CSS IntelliSense does not seem to work in a react 18 based project

### ISSUE THREAD

**Issue by tanmay-m7** [tailwindlabs/tailwindcss-intellisense#1324]
**What version of VS Code are you using?**

version 1.80

**What version of Tailwind CSS IntelliSense are you using?**

v0.14.15

**What version of Tailwind CSS are you using?**

v4.1.4

**What package manager are you using?**

npm

**What operating system are you using?**

macOS

**Tailwind config**

```css
@import "tailwindcss";
@import "tw-animate-css";

@custom-variant dark (&:is(.dark *));

:root {
  --background: oklch(1 0 0);
  --foreground: oklch(0.145 0 0);
  --card: oklch(1 0 0);
  --card-foreground: oklch(0.145 0 0);
  --popover: oklch(1 0 0);
  --popover-foreground: oklch(0.145 0 0);
  --primary: oklch(0.205 0 0);
  --primary-foreground: oklch(0.985 0 0);
  --secondary: oklch(0.97 0 0);
  --secondary-foreground: oklch(0.205 0 0);
  --muted: oklch(0.97 0 0);
  --muted-foreground: oklch(0.556 0 0);
  --accent: oklch(0.97 0 0);
  --accent-foreground: oklch(0.205 0 0);
  --destructive: oklch(0.577 0.245 27.325);
  --destructive-foreground: oklch(0.577 0.245 27.325);
  --border: oklch(0.922 0 0);
  --input: oklch(0.922 0 0);
  --ring: oklch(0.708 0 0);
  --chart-1: oklch(0.646 0.222 41.116);
  --chart-2: oklch(0.6 0.118 184.704);
  --chart-3: oklch(0.398 0.07 227.392);
  --chart-4: oklch(0.828 0.189 84.429);
  --chart-5: oklch(0.769 0.188 70.08);
  --radius: 0.625rem;
  --sidebar: oklch(0.985 0 0);
  --sidebar-foreground: oklch(0.145 0 0);
  --sidebar-primary: oklch(0.205 0 0);
  --sidebar-primary-foreground: oklch(0.985 0 0);
  --sidebar-accent: oklch(0.97 0 0);
  --sidebar-accent-foreground: oklch(0.205 0 0);
  --sidebar-border: oklch(0.922 0 0);
  --sidebar-ring: oklch(0.708 0 0);
}

.dark {
  --background: oklch(0.145 0 0);
  --foreground: oklch(0.985 0 0);
  --card: oklch(0.145 0 0);
  --card-foreground: oklch(0.985 0 0);
  --popover: oklch(0.145 0 0);
  --popover-foreground: oklch(0.985 0 0);
  --primary: oklch(0.985 0 0);
  --primary-foreground: oklch(0.205 0 0);
  --secondary: oklch(0.269 0 0);
  --secondary-foreground: oklch(0.985 0 0);
  --muted: oklch(0.269 0 0);
  --muted-foreground: oklch(0.708 0 0);
  --accent: oklch(0.269 0 0);
  --accent-foreground: oklch(0.985 0 0);
  --destructive: oklch(0.396 0.141 25.723);
  --destructive-foreground: oklch(0.637 0.237 25.331);
  --border: oklch(0.269 0 0);
  --input: oklch(0.269 0 0);
  --ring: oklch(0.439 0 0);
  --chart-1: oklch(0.488 0.243 264.376);
  --chart-2: oklch(0.696 0.17 162.48);
  --chart-3: oklch(0.769 0.188 70.08);
  --chart-4: oklch(0.627 0.265 303.9);
  --chart-5: oklch(0.645 0.246 16.439);
  --sidebar: oklch(0.205 0 0);
  --sidebar-foreground: oklch(0.985 0 0);
  --sidebar-primary: oklch(0.488 0.243 264.376);
  --sidebar-primary-foreground: oklch(0.985 0 0);
  --sidebar-accent: oklch(0.269 0 0);
  --sidebar-accent-foreground: oklch(0.985 0 0);
  --sidebar-border: oklch(0.269 0 0);
  --sidebar-ring: oklch(0.439 0 0);
}

@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --color-card: var(--card);
  --color-card-foreground: var(--card-foreground);
  --color-popover: var(--popover);
  --color-popover-foreground: var(--popover-foreground);
  --color-primary: var(--primary);
  --color-primary-foreground: var(--primary-foreground);
  --color-secondary: var(--secondary);
  --color-secondary-foreground: var(--secondary-foreground);
  --color-muted: var(--muted);
  --color-muted-foreground: var(--muted-foreground);
  --color-accent: var(--accent);
  --color-accent-foreground: var(--accent-foreground);
  --color-destructive: var(--destructive);
  --color-destructive-foreground: var(--destructive-foreground);
  --color-border: var(--border);
  --color-input: var(--input);
  --color-ring: var(--ring);
  --color-chart-1: var(--chart-1);
  --color-chart-2: var(--chart-2);
  --color-chart-3: var(--chart-3);
  --color-chart-4: var(--chart-4);
  --color-chart-5: var(--chart-5);
  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) + 4px);
  --color-sidebar: var(--sidebar);
  --color-sidebar-foreground: var(--sidebar-foreground);
  --color-sidebar-primary: var(--sidebar-primary);
  --color-sidebar-primary-foreground: var(--sidebar-primary-foreground);
  --color-sidebar-accent: var(--sidebar-accent);
  --color-sidebar-accent-foreground: var(--sidebar-accent-foreground);
  --color-sidebar-border: var(--sidebar-border);
  --color-sidebar-ring: var(--sidebar-ring);
}

@layer base {
  * {
    @apply border-border outline-ring/50;
  }
  body {
    @apply bg-background text-foreground;
  }
}

```

**VS Code settings**

```json
{
"tailwindCSS.experimental.configFile": "src/index.css",
  "tailwindCSS.emmetCompletions": true,
  "tailwindCSS.experimental.classRegex": [],
  "tailwindCSS.includeLanguages": {
      "html": "html",
      "javascript": "javascript",
      "typescript": "typescript",
      "jsx": "javascriptreact",
      "tsx": "typescriptreact",
      "vue": "html",
      "blade": "html",
      "php": "html",
      "plaintext": "html"
  }
}

```

**Reproduction URL**

A public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways.

**Describe your issue**

TAILWIND Intellisense output:
```bash
Locating server…
Booting server...
Setting up server…
Listening for messages…
Loading Tailwind CSS projects from the workspace settings.
[Global] Creating projects: [{"folder":"/Users/admin/Documents/df_base","config":"/Users/admin/Documents/df_base/src/index.css","selectors":[{"priority":0,"pattern":"/Users/admin/Documents/df_base/**"}],"user":true,"tailwind":{"version":"4.1.4","features":["css-at-theme","layer:base","content-list","source-inline","source-not"],"isDefaultVersion":false}}]
[Global] Preparing projects...
[Global] Initializing projects...
[src/index.css] Initializing...
[Global] Adding watch patterns: /Users/admin/Documents/df_base/src/index.css, /Users/admin/Documents/df_base/src, /Users/admin/Documents/df_base
[src/index.css] supported features: ["css-at-theme","layer:base","content-list","source-inline","source-not"]
[src/index.css] Loaded tailwindcss v4.1.4: /Users/admin/Documents/df_base/node_modules/tailwindcss
[src/index.css] Building...
[Global] Adding watch patterns: /Users/admin/Documents/df_base/node_modules/tailwindcss/index.css, /Users/admin/Documents/df_base/node_modules/tw-animate-css/dist/tw-animate.css
[Error - 02:10:17] Tailwind CSS: structuredClone is not defined
ReferenceError: structuredClone is not defined
    at Object.compileFn (file:///Users/admin/Documents/df_base/node_modules/tailwindcss/dist/chunk-QMW34FGX.mjs:15:85)
    at vi (file:///Users/admin/Documents/df_base/node_modules/tailwindcss/dist/chunk-QMW34FGX.mjs:15:31121)
    at ur (file:///Users/admin/Documents/df_base/node_modules/tailwindcss/dist/chunk-QMW34FGX.mjs:15:30022)
    at q.factory (file:///Users/admin/Documents/df_base/node_modules/tailwindcss/dist/chunk-QMW34FGX.mjs:15:21760)
    at q.get (file:///Users/admin/Documents/df_base/node_modules/tailwindcss/dist/chunk-QMW34FGX.mjs:3:6680)
    at Object.compileAstNodes (file:///Users/admin/Documents/df_base/node_modules/tailwindcss/dist/chunk-QMW34FGX.mjs:15:22321)
    at ce (file:///Users/admin/Documents/df_base/node_modules/tailwindcss/dist/chunk-QMW34FGX.mjs:15:29397)
    at Object.candidatesToCss (file:///Users/admin/Documents/df_base/node_modules/tailwindcss/dist/chunk-QMW34FGX.mjs:15:22019)
    at Object.compile (/Users/admin/.vscode/extensions/bradlc.vscode-tailwindcss-0.14.15/dist/tailwindServer.js:3578:2564)
    at pc (/Users/admin/.vscode/extensions/bradlc.vscode-tailwindcss-0.14.15/dist/tailwindServer.js:1775:46854)
[Global] Initialized 1 projects
```
