### ISSUE TITLE
v4 intellisense suggests underscore instead of dot in custom utilities

### ISSUE THREAD

**Issue by unional** [tailwindlabs/tailwindcss-intellisense#1328]
**What version of VS Code are you using?**

v1.98.2

**What version of Tailwind CSS IntelliSense are you using?**

v0.14.15

**What version of Tailwind CSS are you using?**

v4.1.0

**What package manager are you using?**

pnpm

**What operating system are you using?**

macOS

**Tailwind config**

```css
@theme static {
  --container-height-3_5: calc(theme(--spacing) * 3.5);
)

@utility container-h-* {
  height: --value(--container-height- *);
}
```

**Reproduction URL**

TBD

**Describe your issue**

On the CSS side, the variable needs avoid `.`,
thus the CSS variable is `--container-height-3_5` instead of `--container-height-3.5`.

The `@utility container-h-* {}` generates/detect `container-h-3.5` instead of `container-h-3_5`.

However the intellisense suggests `container-h-3_5` which does not work.

My guess this is a regression caused by: https://github.com/tailwindlabs/tailwindcss-intellisense/issues/1184

**Comment by thecrypticace** [comment]
This looks to be a bug in `@utility`-driven suggestions specifically. We got those added recently and probably missed this edge case. The `_` should be replaced with a dot when surrounded by digits. Though at this point we consider that a legacy behavior. You can write the variable itself with a dot by escaping it:

```css
@theme static {
  --container-height-3\.5: calc(theme(--spacing) * 3.5);
}

@utility container-h-* {
  height: --value(--container-height- *);
}
```
