### ISSUE TITLE
Incorrect syntax highlighting of `@plugin` directive with options

### ISSUE THREAD

**Issue by EKliptus** [tailwindlabs/tailwindcss-intellisense#1340]
**What version of VS Code are you using?**

v1.98.2

**What version of Tailwind CSS IntelliSense are you using?**

v0.14.16

**What version of Tailwind CSS are you using?**

v4.1.2

**What package manager are you using?**

deno

**What operating system are you using?**

Windows

**Tailwind config**
No config file, just css as config
```css
@import "tailwindcss";
@plugin "@tailwindcss/typography";
@plugin "daisyui" {
  prefix: "d-";
  themes: false;
};
```

**VS Code settings**

```jsonc
// ...
  "files.associations": {
    "*.css": "tailwindcss"
  },
  "editor.quickSuggestions": {
    "strings": "on"
  },
  "tailwindCSS.classFunctions": ["tw", "clsx"],
// ...
```

I have my css file :
```css
@import "tailwindcss";
@plugin "@tailwindcss/typography";
@plugin "daisyui" {
  prefix: "d-";
  themes: false;
}; /* <<<< this semi colon !!! ??? */ 

#container {
  font-family:
    Inter,
    Roboto,
    "Helvetica Neue",
    "Arial Nova",
    "Nimbus Sans",
    Arial,
    sans-serif;
  height: 100%;
}

....
```

Why this semicolon is required after a bracket bloc ?
All formatters delete it !? dprint, biome, prettier, ...
Because when this semicolon is not present after a `@plugin "plugin-name" { <with bloc> }` all code highlighting after the block is incoherent.
malva team used by dprint for css formatting say this semicolon isn't required ? Source : https://github.com/g-plane/malva/issues/28#issuecomment-2818424852

What about ? For now I try many formatter with tailwindcss v4+ and all isn't support v4 !?? Which is the best formatter for tailwindcss files please ???

**Comment by LEstradioto** [comment]
I was about to open the exactly same issue, but found this!

I have the same dillema:
Adding a semicolon fixes syntax highlighting but triggers a compiler error `Error: Unexpected semicolon`
while removing it fixes the error but breaks highlighting.

some related discussions: https://github.com/tailwindlabs/tailwindcss/issues/16964 and [reddit discussion](https://www.reddit.com/r/rails/comments/1kbhsmi/rails_frontend_is_a_pain/)

**Comment by LEstradioto** [comment]
found an ugly workaround to maintain highlighting+compiling:

```css
@import 'tailwindcss';

@plugin 'daisyui' {
  themes: all;
}

/*;*/

body {
  @apply bg-gray-100;
}
```
see the commented bracket
