### ISSUE TITLE
helix: configuring custom language extensions

### ISSUE THREAD

**Issue by againstpetra** [tailwindlabs/tailwindcss-intellisense#1366]
**What version of Helix are you using?**

helix 25.01.1 (e7ac2fcd)

**What version of Tailwind CSS IntelliSense are you using?**

0.14.16

**What version of Tailwind CSS are you using?**

v4

**What package manager are you using?**

homebrew

**What operating system are you using?**

macOS

**Tailwind config**

n/a

**Helix settings**

```toml
[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]
config = { includeLanguages = { "html.tmpl" = "html" } }

[[language]]
name = "gotmpl"
file-types = ["gohtml", { glob = "*.html.tmpl" }]
language-servers = ["gopls", "vscode-html-language-server", "tailwindcss-ls"]
```

**Describe your issue**

the above is how I thought I could get tailwindcss lsp working in files that end with `html.tmpl` from within Helix. the LSP works as expected in html files, but it ~crashes~ doesn't work in the `html.tmpl` files. am I misconfiguring the lsp?

**Comment by thecrypticace** [comment]
It **crashes**? Can you provide an example project I can use to investigate?

I don't know much about Helix but I took a quick peek at their docs and `config = { … }` is used for initialization options. We'll be removing support for includeLanguages in the initialization options eventually. These should be user-level / project-level / language-level settings. I'm not sure how to configure these though.

I'll take a look at Helix + our server either sometime today or tomorrow.

**Comment by againstpetra** [comment]
I shouldn't have said crashes, my bad - it just doesn't seem to work.

> These should be user-level / project-level / language-level settings. I'm not sure how to configure these though.

the second block of the config I posted is how I get Helix to understand that `html.tmpl` files should have the `tailwindcss-ls` lsp used with them. that's how I got `gopls` working with the template files. but I don't get any tailwindcss autocomplete in them

**Comment by thecrypticace** [comment]
yeah sorry I mean that `includeLanguages` as an initialization option will go away eventually.

It's been replaced with (for a while now) a configuration setting: `tailwindCSS.includeLanguages`. Both of these are *language IDs* and not extensions though. So it depends on the language ID sent to the language server by Helix.

I assume that's probably `gotmpl` but I'm not sure. In which case `"html.tmpl" = "html"` should be written `"gotmpl" = "html"`

**Comment by againstpetra** [comment]
> It's been replaced with (for a while now) a configuration setting: `tailwindCSS.includeLanguages`

I'm not sure if Helix actually has a way to change the configuration setting... looking at their [documentation](https://docs.helix-editor.com/languages.html#language-server-configuration) the only reference to configuring the lsp is the `config` key which like you say is for the "server initialization options"

**Comment by thecrypticace** [comment]
I did some source diving and Helix uses `config = {}` for settings *and* initialization options — it doesn't differentiate between them.

I tested and `gotmpl` is the language ID which means you want this config:

```toml
[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]
config = { tailwindCSS = { includeLanguages = { "gotmpl" = "html" } } }

[[language]]
name = "gotmpl"
file-types = ["gohtml", { glob = "*.html.tmpl" }]
language-servers = ["gopls", "vscode-html-language-server", "tailwindcss-ls"]
```

screenshot of that working locally:

<img width="1208" alt="Image" src="https://github.com/user-attachments/assets/2a416a45-51f6-4269-a166-559634125398" />
