### ISSUE TITLE
helix editor: lsp configuration options work on some, except `classFunctions`

### ISSUE THREAD

**Issue by mnpqraven** [tailwindlabs/tailwindcss-intellisense#1380]
**What version of VS Code are you using?**

Not using vs code but helix (25.01.1)

**What version of Tailwind CSS IntelliSense are you using?**

For example: v0.7.0

**What version of Tailwind CSS are you using?**
LSP version 0.14.4
tailwindCSS version 4.1.7

**What package manager are you using?**

pnpm

**What operating system are you using?**

nixos

**Tailwind config**

```toml
[language-server.tailwindcss]
command = "tailwindcss-language-server"
args = ["--stdio"]

# @see https://github.com/tailwindlabs/tailwindcss-intellisense/issues/1366
[language-server.tailwindcss.config.tailwindCSS]
classFunctions = ["cva", "cx", "tw", "clsx"]

```

**Reproduction URL**

i will try to get a reproduction flake up and running later

**Describe your issue**

I've had tailwindcss configured on helix following the [official instructions](https://github.com/helix-editor/helix/wiki/Language-Server-Configurations#tailwindcss). But some configurations (`hovers`) works while others don't (`classFunctions`). Here is a list of what i'm seeing:

- default lsp setup: works, getting autocomplete + hover definition
- add `hovers: false` to configuration: getting autocomplete (expected), not getting hover definition (expected)
- add `classFunctions: ["cva", "cx", "tw", "clsx"]`: no autocomplete + no hover in helper functions, normal behaviour in jsx `className`

**Comment by thecrypticace** [comment]
> LSP version 0.14.4

Ah your LSP version is too old. Support for class functions were added in 0.14.10. If you update it you should be good to go.

Screenshot of them working in helix:

<img width="766" alt="Image" src="https://github.com/user-attachments/assets/198ebde8-36fd-4e73-a837-a00e0dd39831" />

Tested with this config:
```toml
[language-server.tailwindcss]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.tailwindcss.config.tailwindCSS]
classFunctions = ["cva", "cx", "tw", "clsx"]

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss" ]

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss" ]
```
