### ISSUE TITLE
Unknown at rule @view-transition tailwindcss(unknownAtRules)

### ISSUE THREAD

**Issue by ni554n** [tailwindlabs/tailwindcss-intellisense#1392]
**What version of VS Code are you using?**

v1.100.2

**What version of Tailwind CSS IntelliSense are you using?**

v0.14.20

**What version of Tailwind CSS are you using?**

v4.1.8

**What package manager are you using?**

pnpm

**What operating system are you using?**

Windows

**Tailwind config**

n/a

**VS Code settings**

```json
  "files.associations": {
    "*.css": "tailwindcss"
  },
```

**Reproduction URL**

n/a

**Describe your issue**

```css
  @view-transition {    ⚠️ Unknown at rule @view-transition tailwindcss(unknownAtRules)
    navigation: auto;
  }
```
