### ISSUE TITLE
[Feature-request] Trigger suggestion with layer utilities - add custom css

### ISSUE THREAD

**Issue by harrytran998** [tailwindlabs/tailwindcss-intellisense#210]
Example i have this code, but the plugins doesn't trigger suggestion when i press keyword

```css
@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';
@layer utilities {
  .flex-basis-45 {
    flex-basis: 45%;
  }
}
```
