### ISSUE TITLE
Intellisense plugin incorrectly flagging responsive variant as invalid

### ISSUE THREAD

**Issue by lukebennett88** [tailwindlabs/tailwindcss-intellisense#324]
Hey Brad (and Tailwind Labs team).

I created a utility class today like this:

```css
@layer utilities {
  @variants responsive {
    .writing-mode-vertical-lr {
      writing-mode: vertical-lr;
    }
  }
}
```

This is valid and [event mentioned in the docs](https://tailwindcss.com/docs/functions-and-directives#variants).

Unfortunately VS Code gives me the following error message:
`The variant 'responsive' does not exist. Did you mean 'rtl'?(invalidVariant)`

I'm pretty sure this is a bug introduced in the recent release from a few days ago, as I've written code like this before without getting a warning.
