### ISSUE TITLE
More infos about recommendedVariantOrder for stackable variants

### ISSUE THREAD

**Issue by francoismassart** [tailwindlabs/tailwindcss-intellisense#357]
Hi 👋 
I'd like to know more about the `recommendedVariantOrder` rule...

Is it based on https://github.com/tailwindlabs/tailwindcss/blob/master/stubs/defaultConfig.stub.js#L807 ?

Where can I find the details about the recommended order ?
I see that the `focus:` variant is supposed to be use before the `hover:` variant but in `variantOrder`, `hover` is before `focus`...

This is correct:
`md:dark:disabled:focus:hover:bg-gray-400`

And this is marked as invalid:
`md:dark:disabled:hover:focus:bg-gray-400`

Thank you for your response.

**Comment by bradlc** [comment]
Hey @francoismassart. This rule is based on the order that the variants are defined [internally within Tailwind](https://github.com/tailwindlabs/tailwindcss/blob/f1e31682c8e270a163cb43c60ea657c07905e1b7/src/jit/lib/setupContextUtils.js#L459-L468). In most cases the order does not affect the output, but in some cases it can cause malformed CSS. Here's a concrete example:

```css
/* group-hover:dark:uppercase ❌ */
.group:hover .group-hover\:dark .group-hover\:dark\:uppercase {
  text-transform: uppercase;
}

/* dark:group-hover:uppercase ✅ */
.dark .group:hover .dark\:group-hover\:uppercase {
  text-transform: uppercase;
}
```

Hope that helps!
