### ISSUE TITLE
Some problems with intelligence and Tailwindcss itself

### ISSUE THREAD

**Issue by babakfp** [tailwindlabs/tailwindcss-intellisense#648]
**What version of Tailwind CSS IntelliSense are you using?**

v0.9.1

**What version of Tailwind CSS are you using?**

v3.1.8

**Tailwind config**

```js
const config = {
  plugins: [
		({ addUtilities }) => {
			addUtilities({
				'.my-custom-utility': {
					'display': 'block',
					'@apply relative absolute': {},
				},
			})
		},
	],
}
```

**Reproduction URL**

https://play.tailwindcss.com/UqjZYioxIy?file=config

**Describe your issue**

##  1. Intelligence

Not getting intelligence inside functions like `addUtilities` and etc.

## 2. Preview

![Screenshot 2022-10-29 065554](https://user-images.githubusercontent.com/44144724/198835523-7b52b940-d648-4d48-b479-fad02f480ffc.png)

It shows 3 code blocks instead of 1 containing all the styles. I thought there is a problem with the output of Tailwindcss, so I check the output with this command:

```
npx tailwindcss -i ./src/input.css -o ./dist/output.css --watch
```

And the result was as expected:

```
.my-custom-utility {
  display: block;
  position: relative;
  position: absolute;
  position: relative;
}
```

## 3. Order

![Screenshot 2022-10-29 065625](https://user-images.githubusercontent.com/44144724/198835531-360d8cfa-44a1-49b1-82d9-c875649c2d05.png)

Unexpected order of output. As you can see, the order of input and output is not the same. Expected output:

```css
.my-custom-utility {
  display: block;
  position: relative;
  position: relative;
  position: absolute;
}
```

## 4. Duplicate output and intelligence

There is no intelligence for duplicate items. It's probably part of the (1. Intelligence).

Expected output (after removing duplicate styles):

```css
.my-custom-utility {
  display: block;
  position: absolute;
}
```
