### ISSUE TITLE
`invalidConfigPath` error when passing default value for `theme()` function

### ISSUE THREAD

**Issue by javimsevilla** [tailwindlabs/tailwindcss-intellisense#734]
**What version of Tailwind CSS IntelliSense are you using?**

`v0.9.8`

**What version of Tailwind CSS are you using?**

`v3.2.7`

**What package manager are you using?**

`npm`

**What operating system are you using?**

`macOS`

**Tailwind config**

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

**VS Code settings**

```json
{
  "tailwindCSS.emmetCompletions": true
}
```

**Reproduction URL**

https://github.com/javimsevilla/tailwindcss-intellisense-theme-issue

**Describe your issue**

I want to pass a default value for the TailwindCSS `theme()` function as a second argument, but tailwindcss-intellisense shows that this is an error, but it is not, the code works as expected.

<img width="867" alt="image" src="https://user-images.githubusercontent.com/3058446/224815479-db4c10d2-6c31-4267-bdd9-b480352268f0.png">

It doesn't matter what I pass as arguments, it always shows the error if I pass a second argument.

<img width="674" alt="image" src="https://user-images.githubusercontent.com/3058446/224844179-db788b04-b740-4800-a840-61ba27638c54.png">

As a workaround, I can disable the `"tailwindCSS.lint.invalidConfigPath"` property in VS Code settings:

```json
{
  "tailwindCSS.lint.invalidConfigPath": "ignore"
}
```
But, I think this is a bug because it's not the expected behavior.

**Comment by simonhagger** [comment]
Just a quick note on this one for anyone who found their way here from Google search.  I am using Tailwind alongside an Angular application which utilises their Material library: https://material.angular.io/
As of them moving to theming version 3 they advise for themes to be set up in the following way:
```
@mixin theme($theme) {
  @if mat.theme-has($theme, color) {
    @include color($theme);
  }

  @if mat.theme-has($theme, typography) {
    @include typography($theme);
  }
}
```
This triggers the invalidConfigPath error within the Tailwind plugin, so I had to disable it. using the workaround listed above.

**Comment by zer09** [comment]
I'm also using Angular Material, is there a way now to fix this without disabling invalidConfigPath?

**Comment by micobarac** [comment]
Same problem here:

```scss
// Custom Theming for Angular Material
// For more information: https://material.angular.io/guide/theming
@use '@angular/material' as mat;

// Import color themes
@use 'themes' as themes;

// Create the theme object. A theme consists of configurations for individual
// theming systems such as "color" or "typography".
html {
  color-scheme: light;
  @include mat.theme(
    (
      color: (
        primary: themes.$primary-palette,
        tertiary: themes.$tertiary-palette
      )
    )
  );
}
```

```
'(
      color: (
        primary: themes.$primary-palette' does not exist in your theme config.(invalidConfigPath)
```
