### ISSUE TITLE
Colors swatches not shown for colors that use variables

### ISSUE THREAD

**Issue by MuhammadM1998** [tailwindlabs/tailwindcss-intellisense#809]
**What version of VS Code are you using?**
v1.79.2

**What version of Tailwind CSS IntelliSense are you using?**
latest - v0.9.11

**What version of Tailwind CSS are you using?**
3.3.2

**What package manager are you using?**
pnpm

**What operating system are you using?**
Windows

**Tailwind config**

```js
module.exports = {
  theme: {
    extend: {
      colors: {
        accent: {
          DEFAULT: '#00CD7B',
          50: '#86FFCE',
          100: '#71FFC6',
          200: '#48FFB6',
          300: '#20FFA6',
          400: '#00F693',
          500: '#00CD7B',
          600: '#009559',
          700: '#005D38',
          800: '#002516',
          900: '#000000',
          950: '#000000',
        },
        secondary: {
          100: '#E1E1E6',
          200: '#C4C4CC',
          300: '#8D8D99',
          400: '#3A3A41',
          500: '#29292E',
          600: '#202024',
          700: '#121214',
        },
      },
    },
  },
};
```

**VS Code settings**
```json
"tailwindCSS.experimental.classRegex": [
    ["ui:\\s*{([^)]*)\\s*}", "[\"'`]([^\"'`]*).*?[\"'`]"]
]
```

**Reproduction URL**
https://play.tailwindcss.com/PGqCk0dlwn

**Related Issues**
https://github.com/nuxtlabs/ui/issues/357
https://github.com/shadcn/ui/issues/199

**Describe your issue**

As described in both issues, defining colors for NuxtLabs UI or shadcn/ui which both uses tailwind under the hood breaks the color intellisense. 

![249312164-030fe04b-2914-4249-ad6a-1b651d3bc1f5](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/86230182/24e00a23-b3f0-42cc-985f-3cfe7867d92a)

Both libraries owners confirmed they implemented theming with CSS variables with the [recommended way](https://tailwindcss.com/docs/customizing-colors#using-css-variables) to do it in Tailwind. https://github.com/nuxtlabs/ui/issues/357#issuecomment-1611144913, https://github.com/shadcn/ui/issues/199#issuecomment-1513586985

**Comment by milovangudelj** [comment]
I would like to have this too but there's a nubmber of different reasons why this is not supported. First you'd have to start reading user defined stylesheets, and there might be several of them, and build a lot of extra infrastructure to parse the content of those files.

On top of that every variable can have more than one value depending on how the user is defining them. Someone might declare two sets of values depending on the color scheme preference using a media query like `@media (prefers-color-scheme: dark)`, or they could decide to have x number of different themes and specify a `--primary` variable for each one. How are you going to differentiate them and chose the one to display in the editor during development?

Even if you knew there was only one variable and one css file that the extension can read you would still need to update the color parsing logic and manually parse variable values in order to be able to use them with Culori. But for such a simple scenario it doesn't make sense using variables instead of declaring those colors directly in your config file.

It's probably way more complex than this tho, and the team likely doesn't have the resources and/or time to implement such an infrastructure.

**Comment by lexman1958** [comment]
Hi, I am not sure if this has been resolved. I do not seem to get the color decorators in config.js file as shown below:

![Tailwind 2](https://github.com/tailwindlabs/tailwindcss-intellisense/assets/127527088/1b81314d-0d16-4301-90a8-f1150f66b05f)

**Comment by milovangudelj** [comment]
The configuration file doesn't get color swatches and that's expected. Only files specified in your `content` property get parsed and "colorized".

**Comment by lexman1958** [comment]
@milovangudelj thank you for the update. It will be great if its does. Makes life much easier especially if we could get the color palatte as well. Oh well, got to get used to it.

**Comment by milovangudelj** [comment]
Small update I guess. You can still use an extention like [Color Preview](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ColorPreview) or [Colorize](https://marketplace.visualstudio.com/items?itemName=kamikillerto.vscode-colorize) to visualize your configured colors.

The only issue is that it might interfere with Tailwind's extension in files where you used an arbitrary color value like this `bg-[#EA4C89]`. Here tailwind will add it's own color swatch and the other extension will try to do the same. Maybe it's a non issue, but I haven't tried it yet.

**Comment by lexman1958** [comment]
@milovangudelj hi, Thank you for the feed back. I already have Colorize installed but no help. The Color Preview is not for VS Code, bro, its for VS Studio.

**Comment by bradlc** [comment]
I think @milovangudelj's [comment](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/809#issuecomment-1660304770) does a good job of explaining some of the complexities with resolving CSS variables and why we therefore don't show colour decorators for these.

Ultimately CSS variables are just that: variable. So I'm not sure it even makes sense to resolve a CSS variable to a _single_ colour decorator, and we have no immediate plans to change the behaviour here.

If the value of your CSS variable _isn't_ variable then I would consider just using the values directly in your config file like @milovangudelj suggested 👍 

I hope that's understandable!

**Comment by lexman1958** [comment]
@bradlc I totally understand. Its just a nice-to-have thing. Thank you so much.

**Comment by samirant15** [comment]
I have a little solution that works for me in **VSCode** that might work for some of you. You'll need to put a color reference as a comment after the variable:

```css
'light-neutrals': {
  DEFAULT: 'rgb(var(--light-neutrals-default) / <alpha-value>) /* #ffffff */',
  100: 'rgb(var(--light-neutrals-100) / <alpha-value>) /* #ffffff */',
  200: 'rgb(var(--light-neutrals-200) / <alpha-value>) /* #f5f6f7 */',
  300: 'rgb(var(--light-neutrals-300) / <alpha-value>) /* #f2f4f5 */',
  400: 'rgb(var(--light-neutrals-400) / <alpha-value>) /* #ecedee */',
  500: 'rgb(var(--light-neutrals-500) / <alpha-value>) /* #e1e2e3 */',
  600: 'rgb(var(--light-neutrals-600) / <alpha-value>) /* #cacbcc */',
},
```
That way **VSCode** recognizes it:
<img width="725" alt="image" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/18222884/fd599a17-8458-4b11-94bc-9ca4d3578e78">


Note: since you're using variables that means that the color will change, you should only put a reference color in the comment. For instance I have two color variants one for each light/dark theme and put all the light colors as reference because those are my default colors. 

Best of luck!

**Comment by iguana-3d** [comment]
Thank you very much @samirant15 , it worked perfectly!

**Comment by nikosantis** [comment]
> I have a little solution that works for me in **VSCode** that might work for some of you. You'll need to put a color reference as a comment after the variable:
> 
> ```css
> 'light-neutrals': {
>   DEFAULT: 'rgb(var(--light-neutrals-default) / <alpha-value>) /* #ffffff */',
>   100: 'rgb(var(--light-neutrals-100) / <alpha-value>) /* #ffffff */',
>   200: 'rgb(var(--light-neutrals-200) / <alpha-value>) /* #f5f6f7 */',
>   300: 'rgb(var(--light-neutrals-300) / <alpha-value>) /* #f2f4f5 */',
>   400: 'rgb(var(--light-neutrals-400) / <alpha-value>) /* #ecedee */',
>   500: 'rgb(var(--light-neutrals-500) / <alpha-value>) /* #e1e2e3 */',
>   600: 'rgb(var(--light-neutrals-600) / <alpha-value>) /* #cacbcc */',
> },
> ```
> 
> That way **VSCode** recognizes it: <img alt="image" width="725" src="https://private-user-images.githubusercontent.com/18222884/347608544-fd599a17-8458-4b11-94bc-9ca4d3578e78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1ODU2ODUsIm5iZiI6MTczNTU4NTM4NSwicGF0aCI6Ii8xODIyMjg4NC8zNDc2MDg1NDQtZmQ1OTlhMTctODQ1OC00YjExLTk0YmMtOWNhNGQzNTc4ZTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDE5MDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNDY3OGQwMTc5YTQ1NzFlMThkOTU2NmQ0Y2YzZmM5OWI1NmEyYTc5NjQxMzMyYTg2Y2U1ODlhMWIyYTlmMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AX3OVu5v3F6diZUilg_FG5JY67i2k24oj4dy4G-DsGA">
> 
> Note: since you're using variables that means that the color will change, you should only put a reference color in the comment. For instance I have two color variants one for each light/dark theme and put all the light colors as reference because those are my default colors.
> 
> Best of luck!

This solution not work when you need use opacity:
`bg-accent/50` for example. :(

```js
 accent: {
          DEFAULT: 'hsl(var(--accent)) /* hsl(210 40% 96.1%) */',
        },
```

**Comment by PhilStar101** [comment]
Hello! Is there a solution for new tailwind v4? Tried to add color comments to .css file and previews didn't work

**Comment by Merott** [comment]
This isn't the most straightforward or idiomatic solution, but…

In my setup, I happen to have a build step generate my CSS variables from TypeScript definitions. It was for an entirely different purpose, but conveniently, it also makes it possible to generate an additional set of property definitions and provide fallbacks with explicit values for colours that rely on variables.

Essentially, I end up with these definitions in a css file that I import into my `tailwind.css` entrypoint:

```css
@theme inline {
  --background: var(--background, oklch(0.984 0.003 247.858));
  --foreground: var(--foreground, oklch(0.279 0.041 260.031));
}
```

The VSCode extension will pick up the fallback `oklch` values, which come directly from my light theme colours.

<details>
  <summary>In case it helps, here's what I've got</summary>
<br />

Here's the shortened version of my `colors.ts` file:

```ts
// src/theme/colors.ts

import twColors from 'tailwindcss/colors'

const customColors = {
  indigo: {
    50: 'oklch(0.962 0.018 272.314)',
    100: 'oklch(0.93 0.034 272.788)',
    200: 'oklch(0.87 0.065 274.039)',
    300: 'oklch(0.785 0.115 274.713)',
    400: 'oklch(0.673 0.182 276.935)',
    500: 'oklch(0.585 0.233 277.117)',
    600: 'oklch(0.511 0.262 276.966)',
    700: 'oklch(0.457 0.24 277.023)',
    800: 'oklch(0.398 0.195 277.366)',
    900: 'oklch(0.359 0.144 278.697)',
    950: 'oklch(0.257 0.09 281.288)',
  },
}

const baseColors = {
  black: twColors.black,
  white: twColors.white,
  transparent: twColors.transparent,

  brand: customColors.indigo,
  neutral: twColors.slate,
} as const

const allColors = {
  ...baseColors,

  /***********************************************************/
  /* Semantic, light/dark color groups are prefixed with `$` */
  /***********************************************************/

  $background: {
    light: baseColors.neutral[50],
    dark: baseColors.neutral[900],
  },
  $foreground: {
    light: baseColors.neutral[800],
    dark: baseColors.neutral[100],
  },
} as const

export default allColors
```

This is the script that generates the CSS file:

```ts
// tools/scripts/codegen-css-colors.ts

import fs from 'node:fs'

import prettier from 'prettier'

import themeColors from '@/theme/colors'

const baseColors = Object.entries(themeColors).flatMap(([group, value]) => {
  if (group.startsWith('$')) {
    return []
  }

  if (typeof value === 'string') {
    return `--color-${group}: ${value};`
  }

  return [
    `\n/* --- ${group} --- */`,
    ...Object.entries(value).map(([shade, value]) => {
      return `--color-${group}-${shade}: ${value};`
    }),
  ]
})

type ColorTuple = [name: string, value: string]
const lightColors: ColorTuple[] = []
const darkColors: ColorTuple[] = []

Object.entries(themeColors).forEach(([name, value]) => {
  if (!name.startsWith('$') || typeof value !== 'object') return []

  if ('light' in value) {
    lightColors.push([name.slice(1), value.light])
  }

  if ('dark' in value) {
    darkColors.push([name.slice(1), value.dark])
  }
})

const themeVariables = {
  light: lightColors.map(([name, value]) => `--${name}: ${value};`),
  dark: darkColors.map(([name, value]) => `--${name}: ${value};`),
}

// Development-only fallback to light colors for VSCode inline previews
const editorPreviewFallbacks =
  process.env.NODE_ENV === 'development'
    ? lightColors.map(([name, value]) => `--${name}: var(--${name}, ${value});`)
    : []

const colorVariableReferences = lightColors.map(([name]) => {
  return `--color-${name}: var(--${name});`
})

const css = `
/*************************** DO NOT EDIT MANUALLY ***************************/
/* Auto-generated from 'colors.ts' with 'pnpm codegen:css-colors' */

@theme {
  --color-*: initial;

  ${baseColors.join('\n')}
}

:root {
  ${themeVariables.light.join('\n')}
}

.dark {
  ${themeVariables.dark.join('\n')}
}

@theme inline {
  /*
    NOTE: This group of colors is only generated in development to help the
    VSCode Tailwind CSS extension show color previews within the editor
  */

    ${editorPreviewFallbacks.join('\n  ')}
}

@theme inline {
  ${colorVariableReferences.join('\n')}
}
`

fs.writeFileSync(
  'src/theme/.generated/colors.css',
  await prettier.format(css, { parser: 'css' }),
)
``` 

The important bit is `editorPreviewFallbacks` which sets fallback values for each variable definition to the explicit colour values used in my default (light) theme.

I have the script running alongside the build in watch mode using `tsx`:

```sh
tsx watch tools/scripts/codegen-css-colors.ts
```

Which generates a CSS file like this:

```css
/*************************** DO NOT EDIT MANUALLY ***************************/
/* Auto-generated from 'colors.ts' with 'pnpm codegen:css-colors' */

@theme {
  --color-*: initial;

  --color-black: #000;
  --color-white: #fff;
  --color-transparent: transparent;

  /* --- brand --- */
  --color-brand-50: oklch(0.962 0.018 272.314);
  --color-brand-100: oklch(0.93 0.034 272.788);
  --color-brand-200: oklch(0.87 0.065 274.039);
  --color-brand-300: oklch(0.785 0.115 274.713);
  --color-brand-400: oklch(0.673 0.182 276.935);
  --color-brand-500: oklch(0.585 0.233 277.117);
  --color-brand-600: oklch(0.511 0.262 276.966);
  --color-brand-700: oklch(0.457 0.24 277.023);
  --color-brand-800: oklch(0.398 0.195 277.366);
  --color-brand-900: oklch(0.359 0.144 278.697);
  --color-brand-950: oklch(0.257 0.09 281.288);

  /* --- neutral --- */
  --color-neutral-50: oklch(0.984 0.003 247.858);
  --color-neutral-100: oklch(0.968 0.007 247.896);
  --color-neutral-200: oklch(0.929 0.013 255.508);
  --color-neutral-300: oklch(0.869 0.022 252.894);
  --color-neutral-400: oklch(0.704 0.04 256.788);
  --color-neutral-500: oklch(0.554 0.046 257.417);
  --color-neutral-600: oklch(0.446 0.043 257.281);
  --color-neutral-700: oklch(0.372 0.044 257.287);
  --color-neutral-800: oklch(0.279 0.041 260.031);
  --color-neutral-900: oklch(0.208 0.042 265.755);
  --color-neutral-950: oklch(0.129 0.042 264.695);
}

:root {
  --background: oklch(0.984 0.003 247.858);
  --foreground: oklch(0.279 0.041 260.031);
}

.dark {
  --background: oklch(0.208 0.042 265.755);
  --foreground: oklch(0.968 0.007 247.896);
}

@theme inline {
  /*
    NOTE: This group of colors is only generated in development to help the
    VSCode Tailwind CSS extension show color previews within the editor
  */

  --background: var(--background, oklch(0.984 0.003 247.858));
  --foreground: var(--foreground, oklch(0.279 0.041 260.031));
}

@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
}
```

I import the generated CSS file (which is gitignored) into my main `tailwind.css` entrypoint:

```css
/* tailwind.css */

@import 'tailwindcss';
@import './.generated/colors.css';

@layer base {
  body {
    @apply antialiased selection:bg-primary/25 dark:selection:bg-primary/40;
  }
}
```

</details>
