### ISSUE TITLE
Support for light-dark() colors 

### ISSUE THREAD

**Issue by smhmd** [tailwindlabs/tailwindcss-intellisense#940]
**What version of VS Code are you using?**

Version: 1.87.2

**What version of Tailwind CSS IntelliSense are you using?**

v0.11.60 (pre-release)

**What version of Tailwind CSS are you using?**

4.0.0-alpha.10

**What package manager are you using?**

pnpm

**What operating system are you using?**

macOS

**Tailwind config**

```css
@import 'tailwindcss';

:root {
  color-scheme: light dark;
}

@theme {
  --color-*: initial;
  
  --text-color-brand-primary: light-dark(white, black);
  --text-color-brand-secondary: blue;
}
```

**VS Code settings**

n/a

**Reproduction URL**

Please, insist if needed and I'll create one 🙏🏼 , otherwise, I think the description is self explanatory

**Describe your issue**

When using `light-dark()` CSS function ([MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark)), the intellisense loses its color. I think adding both colors makes some sense.

<img width="1488" alt="image" src="https://github.com/tailwindlabs/tailwindcss-intellisense/assets/46059092/aa07c912-c05b-46ce-9d2b-fe8b97dcd002">
